"""Configuration generation for the installation wizard.

This module handles generating configuration files and activation
scripts for the installed pipeline components.
"""

import json
from pathlib import Path
from typing import TYPE_CHECKING, Dict, Optional

from env_config import INSTALL_DIR

from .utils import Colors, print_header, print_info, print_success

if TYPE_CHECKING:
    from .conda import CondaEnvironmentManager


class ConfigurationGenerator:
    """Generates configuration files and activation scripts."""

    def __init__(self, conda_manager: 'CondaEnvironmentManager', base_dir: Optional[Path] = None):
        self.conda_manager = conda_manager
        self.base_dir = base_dir or INSTALL_DIR

    def generate_config_dict(self) -> Dict:
        """Generate configuration dictionary.

        Returns:
            Configuration dict
        """
        python_exe = self.conda_manager.get_python_executable()

        config = {
            "version": "1.0",
            "environment": self.conda_manager.env_name,
            "paths": {
                "base": str(self.base_dir),
                "wham": str(self.base_dir / "WHAM"),
                "econ": str(self.base_dir / "ECON"),
                "smplx_models": str(self.base_dir / "smplx_models"),
            },
            "python": str(python_exe) if python_exe else None,
            "conda_activate": self.conda_manager.get_activation_command(),
        }

        return config

    def write_config_file(self) -> Path:
        """Write configuration to JSON file.

        Returns:
            Path to config file
        """
        config = self.generate_config_dict()
        config_file = self.base_dir / "config.json"

        self.base_dir.mkdir(parents=True, exist_ok=True)

        with open(config_file, 'w') as f:
            json.dump(config, indent=2, fp=f)

        print_success(f"Configuration saved to {config_file}")
        return config_file

    def generate_activation_script(self) -> str:
        """Generate shell activation script.

        Returns:
            Activation script content
        """
        script = f"""#!/bin/bash
# VFX Pipeline Environment Activation Script
# Generated by installation wizard

# Activate conda environment
{self.conda_manager.get_activation_command()}

# Set up Python path
export PYTHONPATH="${{PYTHONPATH}}:{self.base_dir / "WHAM"}:{self.base_dir / "ECON"}"

# Set up environment variables
export VFX_PIPELINE_BASE="{self.base_dir}"
export WHAM_DIR="{self.base_dir / "WHAM"}"
export ECON_DIR="{self.base_dir / "ECON"}"
export SMPLX_MODEL_DIR="{self.base_dir / "smplx_models"}"

echo "✓ VFX Pipeline environment activated"
echo "  Environment: {self.conda_manager.env_name}"
echo "  Base directory: {self.base_dir}"
echo ""
echo "Available commands:"
echo "  python scripts/run_pipeline.py --help"
echo "  python scripts/run_mocap.py --help"
"""
        return script

    def write_activation_script(self) -> Path:
        """Write activation script to file.

        Returns:
            Path to activation script
        """
        script = self.generate_activation_script()
        script_file = self.base_dir / "activate.sh"

        with open(script_file, 'w') as f:
            f.write(script)

        # Make executable
        script_file.chmod(0o755)

        print_success(f"Activation script saved to {script_file}")
        print_info(f"Source with: source {script_file}")
        return script_file

    def generate_all(self):
        """Generate all configuration files."""
        print_header("Generating Configuration")

        self.write_config_file()
        self.write_activation_script()

        print()
        print_info("Configuration complete!")
        print_info("To activate the environment:")
        print(f"  {Colors.OKBLUE}{self.conda_manager.get_activation_command()}{Colors.ENDC}")
        print("  or")
        print(f"  {Colors.OKBLUE}source {self.base_dir / 'activate.sh'}{Colors.ENDC}")
