"""Configuration generation for the installation wizard.

This module handles generating configuration files and activation
scripts for the installed pipeline components.
"""

import json
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Dict, Optional

from env_config import INSTALL_DIR

from .utils import Colors, print_header, print_info, print_success

if TYPE_CHECKING:
    from .conda import CondaEnvironmentManager


def _is_windows() -> bool:
    """Check if running on Windows."""
    return sys.platform == "win32"


class ConfigurationGenerator:
    """Generates configuration files and activation scripts."""

    def __init__(self, conda_manager: 'CondaEnvironmentManager', base_dir: Optional[Path] = None):
        self.conda_manager = conda_manager
        self.base_dir = base_dir or INSTALL_DIR

    def generate_config_dict(self) -> Dict:
        """Generate configuration dictionary.

        Returns:
            Configuration dict
        """
        python_exe = self.conda_manager.get_python_executable()

        config = {
            "version": "1.0",
            "environment": self.conda_manager.env_name,
            "paths": {
                "base": str(self.base_dir),
                "gvhmr": str(self.base_dir / "GVHMR"),
                "econ": str(self.base_dir / "ECON"),
                "smplx_models": str(self.base_dir / "smplx_models"),
            },
            "python": str(python_exe) if python_exe else None,
            "conda_activate": self.conda_manager.get_activation_command(),
        }

        return config

    def write_config_file(self) -> Path:
        """Write configuration to JSON file.

        Returns:
            Path to config file
        """
        config = self.generate_config_dict()
        config_file = self.base_dir / "config.json"

        self.base_dir.mkdir(parents=True, exist_ok=True)

        with open(config_file, 'w', encoding='utf-8') as f:
            json.dump(config, indent=2, fp=f)

        print_success(f"Configuration saved to {config_file}")
        return config_file

    def generate_activation_script(self) -> str:
        """Generate shell activation script.

        Returns:
            Activation script content
        """
        script = f"""#!/bin/bash
# VFX Pipeline Environment Activation Script
# Generated by installation wizard

# Activate conda environment
{self.conda_manager.get_activation_command()}

# Set up Python path
export PYTHONPATH="${{PYTHONPATH}}:{self.base_dir / "GVHMR"}:{self.base_dir / "ECON"}"

# Set up environment variables
export VFX_PIPELINE_BASE="{self.base_dir}"
export GVHMR_DIR="{self.base_dir / "GVHMR"}"
export ECON_DIR="{self.base_dir / "ECON"}"
export SMPLX_MODEL_DIR="{self.base_dir / "smplx_models"}"

echo "OK VFX Pipeline environment activated"
echo "  Environment: {self.conda_manager.env_name}"
echo "  Base directory: {self.base_dir}"
echo ""
echo "Available commands:"
echo "  python scripts/run_pipeline.py --help"
echo "  python scripts/run_mocap.py --help"
"""
        return script

    def generate_activation_script_powershell(self) -> str:
        """Generate PowerShell activation script for Windows.

        Returns:
            PowerShell activation script content
        """
        base_dir_win = str(self.base_dir).replace('/', '\\')
        gvhmr_dir_win = str(self.base_dir / "GVHMR").replace('/', '\\')
        econ_dir_win = str(self.base_dir / "ECON").replace('/', '\\')
        smplx_dir_win = str(self.base_dir / "smplx_models").replace('/', '\\')

        script = f"""# VFX Pipeline Environment Activation Script (PowerShell)
# Generated by installation wizard
# Usage: . .\\activate.ps1

# Check if conda is initialized for PowerShell
if (-not (Get-Command conda -ErrorAction SilentlyContinue)) {{
    Write-Host "ERROR: conda not found in PATH" -ForegroundColor Red
    Write-Host "Run this command first (as Administrator or in new terminal):" -ForegroundColor Yellow
    Write-Host "  conda init powershell" -ForegroundColor Cyan
    Write-Host "Then restart PowerShell and try again." -ForegroundColor Yellow
    return
}}

# Activate conda environment
conda activate {self.conda_manager.env_name}

# Set up Python path (handle empty PYTHONPATH)
if ($env:PYTHONPATH) {{
    $env:PYTHONPATH = "$env:PYTHONPATH;{gvhmr_dir_win};{econ_dir_win}"
}} else {{
    $env:PYTHONPATH = "{gvhmr_dir_win};{econ_dir_win}"
}}

# Set up environment variables (quoted for paths with spaces)
$env:VFX_PIPELINE_BASE = "{base_dir_win}"
$env:GVHMR_DIR = "{gvhmr_dir_win}"
$env:ECON_DIR = "{econ_dir_win}"
$env:SMPLX_MODEL_DIR = "{smplx_dir_win}"

Write-Host "VFX Pipeline environment activated" -ForegroundColor Green
Write-Host "  Environment: {self.conda_manager.env_name}"
Write-Host "  Base directory: {base_dir_win}"
Write-Host ""
Write-Host "Available commands:"
Write-Host "  python scripts\\run_pipeline.py --help"
Write-Host "  python scripts\\run_mocap.py --help"
"""
        return script

    def generate_activation_script_batch(self) -> str:
        """Generate Batch activation script for Windows CMD.

        Returns:
            Batch activation script content
        """
        base_dir_win = str(self.base_dir).replace('/', '\\')
        gvhmr_dir_win = str(self.base_dir / "GVHMR").replace('/', '\\')
        econ_dir_win = str(self.base_dir / "ECON").replace('/', '\\')
        smplx_dir_win = str(self.base_dir / "smplx_models").replace('/', '\\')

        script = f"""@echo off
REM VFX Pipeline Environment Activation Script (Batch)
REM Generated by installation wizard
REM Usage: activate.bat

REM Activate conda environment
call conda activate {self.conda_manager.env_name}

REM Set up Python path (handle empty PYTHONPATH)
if defined PYTHONPATH (
    set "PYTHONPATH=%PYTHONPATH%;{gvhmr_dir_win};{econ_dir_win}"
) else (
    set "PYTHONPATH={gvhmr_dir_win};{econ_dir_win}"
)

REM Set up environment variables (quoted for paths with spaces)
set "VFX_PIPELINE_BASE={base_dir_win}"
set "GVHMR_DIR={gvhmr_dir_win}"
set "ECON_DIR={econ_dir_win}"
set "SMPLX_MODEL_DIR={smplx_dir_win}"

echo.
echo VFX Pipeline environment activated
echo   Environment: {self.conda_manager.env_name}
echo   Base directory: {base_dir_win}
echo.
echo Available commands:
echo   python scripts\\run_pipeline.py --help
echo   python scripts\\run_mocap.py --help
"""
        return script

    def write_activation_script(self) -> Path:
        """Write activation script(s) to file.

        Generates platform-appropriate scripts:
        - Linux/macOS: activate.sh
        - Windows: activate.ps1 and activate.bat

        Returns:
            Path to primary activation script for current platform
        """
        self.base_dir.mkdir(parents=True, exist_ok=True)

        bash_script = self.generate_activation_script()
        bash_file = self.base_dir / "activate.sh"
        with open(bash_file, 'w', newline='\n', encoding='utf-8') as f:
            f.write(bash_script)
        if not _is_windows():
            bash_file.chmod(0o755)

        ps1_script = self.generate_activation_script_powershell()
        ps1_file = self.base_dir / "activate.ps1"
        with open(ps1_file, 'w', newline='\r\n', encoding='utf-8') as f:
            f.write(ps1_script)

        bat_script = self.generate_activation_script_batch()
        bat_file = self.base_dir / "activate.bat"
        with open(bat_file, 'w', newline='\r\n', encoding='utf-8') as f:
            f.write(bat_script)

        if _is_windows():
            print_success(f"Activation scripts saved to {self.base_dir}")
            print_info(f"PowerShell: . {ps1_file}")
            print_info(f"CMD:        {bat_file}")
            return ps1_file
        else:
            print_success(f"Activation scripts saved to {self.base_dir}")
            print_info(f"Source with: source {bash_file}")
            return bash_file

    def generate_all(self):
        """Generate all configuration files."""
        print_header("Generating Configuration")

        self.write_config_file()
        self.write_activation_script()

        print()
        print_info("Configuration complete!")
        print_info("To activate the environment:")
        print(f"  {Colors.OKBLUE}{self.conda_manager.get_activation_command()}{Colors.ENDC}")
        print("  or")
        if _is_windows():
            print(f"  {Colors.OKBLUE}PowerShell: . {self.base_dir / 'activate.ps1'}{Colors.ENDC}")
            print(f"  {Colors.OKBLUE}CMD:        {self.base_dir / 'activate.bat'}{Colors.ENDC}")
        else:
            print(f"  {Colors.OKBLUE}source {self.base_dir / 'activate.sh'}{Colors.ENDC}")
