#!/bin/bash
# VFX Ingest Platform - Docker Build Configuration Setup
# Detects GPU architecture and saves configuration to .env file

set -e

# Color output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get repo root directory (parent of scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${REPO_ROOT}/.env"

echo "Detecting GPU architecture for Docker build..."
echo ""

# Run detection script
CUDA_ARCH=$(cd "$REPO_ROOT" && ./scripts/detect_cuda_arch.sh)

# Show what was detected
if command -v nvidia-smi &> /dev/null; then
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1 2>/dev/null || echo "Unknown GPU")
    if [ "$CUDA_ARCH" = "7.5 8.6 8.9" ]; then
        echo -e "${YELLOW}⚠️  Could not detect specific GPU, using multi-arch default${NC}"
        echo "   Build will support: RTX 20xx/30xx/40xx series"
    else
        echo -e "${GREEN}✓ Detected: $GPU_NAME${NC}"
        echo "  CUDA compute capability: $CUDA_ARCH"
        echo "  Build will be optimized for this GPU only (faster build)"
    fi
else
    echo -e "${YELLOW}⚠️  nvidia-smi not found, using multi-arch default${NC}"
    echo "   Build will support: RTX 20xx/30xx/40xx series"
fi

echo ""

# Save to .env file
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup_build.sh - Run setup_build.sh to regenerate
# Generated: $(date)
#
# CUDA architecture for Docker build
# Values: single arch (e.g., "8.6") or multiple (e.g., "7.5 8.6 8.9")
CUDA_ARCH=${CUDA_ARCH}

# Optional: Override volume paths for docker-compose
# Uncomment and modify if you want custom locations
# VFX_MODELS_DIR=./.vfx_pipeline/models
# VFX_PROJECTS_DIR=../vfx_projects
EOF

echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""
echo "Next steps:"
echo "  docker compose build    # Build Docker image with detected GPU settings"
echo "  ./scripts/run_docker.sh # Run the pipeline"
echo ""
echo "Note: Re-run this script if you upgrade your GPU"
